name: Notify Integration Release (Manual)
on:
  workflow_dispatch:
    inputs:
      version:
        description: "A semver"
        default: 0.0.1
        required: false
      branch:
        description: "A branch or SHA"
        default: "main"
        required: false
jobs:
  notify-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        integration_identifier:
          - "waypoint/aws-alb"
          - "waypoint/aws-ami"
          - "waypoint/aws-ec2"
          - "waypoint/aws-ecr-pull"
          # - "waypoint/aws-ecr"
          # - "waypoint/aws-ecs"
          # - "waypoint/aws-lambda"
          # - "waypoint/aws-ssm"
          # - "waypoint/azure-container-instance"
          # - "waypoint/consul"
          # - "waypoint/docker-pull"
          # - "waypoint/docker-ref"
          - "waypoint/docker"
          # - "waypoint/exec"
          # - "waypoint/files"
          # - "waypoint/google-cloud-run"
          # - "waypoint/helm"
          # - "waypoint/kubernetes-apply"
          # - "waypoint/kubernetes"
          # - "waypoint/lambda-function-url"
          # - "waypoint/nomad-jobspec-canary"
          # - "waypoint/nomad-jobspec"
          # - "waypoint/nomad"
          # - "waypoint/null"
          # - "waypoint/pack"
          # - "waypoint/terraform-cloud"
          # - "waypoint/vault"
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Checkout integration-release-action
        uses: actions/checkout@v2
        with:
          repository: hashicorp/integration-release-action
          path: ./integration-release-action
      - name: Notify Release
        uses: ./integration-release-action
        with:
          integration_identifier: ${{ matrix.integration_identifier }}
          release_version: ${{ github.event.inputs.version }}
          release_sha: ${{ github.event.inputs.branch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
