on: [deployment_status]

jobs:
  test-link-rewrites:
    if: github.event.deployment_status.state == 'success'
    uses: hashicorp/dev-portal/.github/workflows/docs-content-link-rewrites-e2e.yml
    with:
      repo-owner: "hashicorp"
      repo-name: "waypoint"
      commit-sha: ${{ github.sha }}
      main-branch-preview-url: "https://waypoint-git-main-hashicorp.vercel.app/"
      pr-branch-preview-url: "https://waypoint-git-docs-ambmigrate-link-formats-hashicorp.vercel.app/"
